### AWS Auth Configuration ###
provider "aws" {
  profile    = var.profile
  region     = lookup(var.aws_region, var.region)
}

module "iam" {
  source = "./modules/iam"
}

### Modules ###

# module "example" {
#   source = "./modules/functions/example"
#   lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
#   function_example_name = var.function_example_name
#   function_example_url = var.function_example_url

#   region = var.region
#   region_wrapper = var.region_wrapper_python
#   access_token = var.access_token
#   realm = var.realm
#   metrics_url = var.metrics_url
#   metrics_tracing = var.metrics_tracing
#   apm_environment = var.apm_environment
# }

# ## Print the random_id generated by module example
# output "random_id_example" {
#   value = module.example.example
# }

# ## Print the url generated by the example function to enable easy testing
# output "example_base_url" {
#   value = module.example.base_url
# }

module "retailorder" {
  source = "./modules/functions/retailorder"
  lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
  lambda_function_retailorderline_arn = module.retailorderline.lambda_function_retailorderline_arn
  retailorderprice_base_url = module.retailorderprice.base_url
  function_retailorder_name = var.function_retailorder_name
  function_retailorder_url = var.function_retailorder_url
  
  region = var.region
  region_wrapper = var.region_wrapper_python
  access_token = var.access_token
  realm = var.realm
  metrics_url = var.metrics_url
  metrics_tracing = var.metrics_tracing
  apm_environment = var.apm_environment
}

## Print the random_id generated by module retailorder
output "random_id_retailorder" {
  value = module.retailorder.random_id_retailorder
}

## Print the url generated by the function to enable easy testing
output "retailorder_base_url" {
  value = module.retailorder.base_url
}

module "retailorderline" {
  source = "./modules/functions/retailorderline"
  lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
  function_retailorderline_name = var.function_retailorderline_name
  function_retailorderline_url = var.function_retailorderline_url

  region = var.region
  region_wrapper = var.region_wrapper_python
  access_token = var.access_token
  realm = var.realm
  metrics_url = var.metrics_url
  metrics_tracing = var.metrics_tracing
  apm_environment = var.apm_environment
}

## Print the random_id generated by module retailorderline
output "random_id_retailorderline" {
  value = module.retailorderline.random_id_retailorderline
}

module "retailorderprice" {
  source = "./modules/functions/retailorderprice"
  lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
  retaildiscount_invoke_url = module.retaildiscount.invoke_url
  retaildiscount_function_name = module.retaildiscount.function_name
  retaildiscount_stage_name = module.retaildiscount.stage_name
  function_retailorderprice_name = var.function_retailorderprice_name
  function_retailorderprice_url = var.function_retailorderprice_url
  
  region = var.region
  region_wrapper = var.region_wrapper_nodejs
  access_token = var.access_token
  realm = var.realm
  metrics_url = var.metrics_url
  metrics_tracing = var.metrics_tracing
  apm_environment = var.apm_environment
}

## Print the random_id generated by module retailorderprice
output "random_id_retailorderprice" {
  value = module.retailorderprice.random_id_retailorderprice
}

## Print the url generated by the function to enable easy testing
output "retailorderprice_base_url" {
  value = module.retailorderprice.base_url
}

module "retaildiscount" {
  source = "./modules/functions/retaildiscount"
  lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
  function_retaildiscount_name = var.function_retaildiscount_name
  function_retaildiscount_url = var.function_retaildiscount_url

  invoke_url_tmp = module.retaildiscount.invoke_url_tmp

  region = var.region
  region_wrapper = var.region_wrapper_nodejs
  access_token = var.access_token
  realm = var.realm
  metrics_url = var.metrics_url
  metrics_tracing = var.metrics_tracing
  apm_environment = var.apm_environment
}

## Print the random_id generated by module retaildiscount
output "random_id_retaildiscount" {
  value = module.retaildiscount.random_id_retaildiscount
}

## Print the invoke url generated by the function
output "retaildiscount_invoke_url" {
  value = module.retaildiscount.invoke_url
}

## Print the stage_name generated by the function
output "retaildiscount_stage_name" {
  value = module.retaildiscount.stage_name
}

## Print the rest_api_id generated by the function
output "retaildiscount_rest_api_id" {
  value = module.retaildiscount.rest_api_id
}

## Print the Function Name
output "retaildiscount_function_name" {
  value = module.retaildiscount.function_name
}