### AWS Auth Configuration ###
provider "aws" {
  profile    = var.profile
  region     = lookup(var.aws_region, var.region)
}

module "iam" {
  source = "./modules/iam"
}

### Modules ###

# module "example" {
#   source = "./modules/functions/example"
#   lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
#   function_example_name = var.function_example_name
#   function_example_url = var.function_example_url

#   region = var.region
#   region_wrapper = var.region_wrapper
#   access_token = var.access_token
#   realm = var.realm
#   metrics_url = var.metrics_url
#   metrics_tracing = var.metrics_tracing
#   apm_environment = var.apm_environment
# }

# ## Print the random_id generated by module example
# output "random_id_example" {
#   value = module.example.random_id_one
# }

# ## Print the url generated by the example function to enable easy testing
# output "example_base_url" {
#   value = module.example.base_url
# }

module "one" {
  source = "./modules/functions/one"
  lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
  lambda_function_two_arn = module.two.lambda_function_two_arn
  function_one_name = var.function_one_name
  function_one_url = var.function_one_url

  region = var.region
  region_wrapper = var.region_wrapper
  access_token = var.access_token
  realm = var.realm
  metrics_url = var.metrics_url
  metrics_tracing = var.metrics_tracing
  apm_environment = var.apm_environment
}

## Print the random_id generated by module one
output "random_id_one" {
  value = module.one.random_id_one
}

## Print the url generated by the function to enable easy testing
output "one_base_url" {
  value = module.one.base_url
}

module "two" {
  source = "./modules/functions/two"
  lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
  function_two_name = var.function_two_name
  function_two_url = var.function_two_url

  region = var.region
  region_wrapper = var.region_wrapper
  access_token = var.access_token
  realm = var.realm
  metrics_url = var.metrics_url
  metrics_tracing = var.metrics_tracing
  apm_environment = var.apm_environment
}


## Print the random_id generated by module two
output "random_id_two" {
  value = module.two.random_id_two
}

# ## Print the url generated by the function to enable easy testing
# output "two_base_url" {
#   value = module.two.base_url
# }

module "three" {
  source = "./modules/functions/three"
  lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
  function_three_name = var.function_three_name
  function_three_url = var.function_three_url

  region = var.region
  region_wrapper = var.region_wrapper
  access_token = var.access_token
  realm = var.realm
  metrics_url = var.metrics_url
  metrics_tracing = var.metrics_tracing
  apm_environment = var.apm_environment
}

## Print the random_id generated by module three
output "random_id_three" {
  value = module.three.random_id_three
}

## Print the url generated by the function to enable easy testing
output "three_base_url" {
  value = module.three.base_url
}

module "four" {
  source = "./modules/functions/four"
  lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
  function_four_name = var.function_four_name
  function_four_url = var.function_four_url

  region = var.region
  region_wrapper = var.region_wrapper
  access_token = var.access_token
  realm = var.realm
  metrics_url = var.metrics_url
  metrics_tracing = var.metrics_tracing
  apm_environment = var.apm_environment
}

## Print the random_id generated by module four
output "random_id_four" {
  value = module.four.random_id_four
}

## Print the url generated by the function to enable easy testing
output "four_base_url" {
  value = module.four.base_url
}

# module "xxx" {
#   source = "./modules/functions/xxx"
#   lambda_initiate_lambda_role_arn = module.iam.lambda_initiate_lambda_role_arn
#   function_xxx_name = var.function_xxx_name
#   function_xxx_url = var.function_xxx_url

#   region = var.region
#   region_wrapper = var.region_wrapper
#   access_token = var.access_token
#   realm = var.realm
#   metrics_url = var.metrics_url
#   metrics_tracing = var.metrics_tracing
#   apm_environment = var.apm_environment
# }

# ## Print the random_id generated by module xxx
# output "random_id_xxx" {
#   value = module.xxx.random_id_xxx
# }

# ## Print the url generated by the function to enable easy testing
# output "xxx_base_url" {
#   value = module.xxx.base_url
# }